var classes = [
    {
        "name": "App\\Calculator",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getServer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setServer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getServersAvailableResources",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resetServersAvailableResources",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getVirtualMachines",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setVirtualMachines",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addVirtualMachine",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculateNeededServers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "allocateAvailableResources",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isVirtualMachineFits",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 10,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 21,
        "ccn": 11,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Server",
            "InvalidArgumentException",
            "App\\Server",
            "App\\Server",
            "App\\Server",
            "Exception",
            "App\\VirtualMachine",
            "App\\VirtualMachine",
            "App\\Server",
            "App\\VirtualMachine"
        ],
        "parents": [],
        "lcom": 1,
        "length": 101,
        "vocabulary": 16,
        "volume": 404,
        "difficulty": 21.3,
        "effort": 8605.2,
        "level": 0.05,
        "bugs": 0.13,
        "time": 478,
        "intelligentContent": 18.97,
        "number_operators": 30,
        "number_operands": 71,
        "number_operators_unique": 6,
        "number_operands_unique": 10,
        "cloc": 16,
        "loc": 102,
        "lloc": 86,
        "mi": 66.86,
        "mIwoC": 38.07,
        "commentWeight": 28.79,
        "kanDefect": 1.1,
        "relativeStructuralComplexity": 225,
        "relativeDataComplexity": 0.55,
        "relativeSystemComplexity": 225.55,
        "totalStructuralComplexity": 2475,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 2481,
        "package": "App\\",
        "pageRank": 0.07,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Server",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getCpu",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCpu",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRam",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRam",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHdd",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setHdd",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 3,
        "wmc": 6,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\ServerInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 18,
        "vocabulary": 6,
        "volume": 46.53,
        "difficulty": 3,
        "effort": 139.59,
        "level": 0.33,
        "bugs": 0.02,
        "time": 8,
        "intelligentContent": 15.51,
        "number_operators": 6,
        "number_operands": 12,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 18,
        "loc": 47,
        "lloc": 29,
        "mi": 97.21,
        "mIwoC": 56.29,
        "commentWeight": 40.92,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 21,
        "totalSystemComplexity": 21,
        "package": "App\\",
        "pageRank": 0.14,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\ServerTrait",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCpu",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRam",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHdd",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "InvalidArgumentException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 31,
        "vocabulary": 11,
        "volume": 107.24,
        "difficulty": 7.92,
        "effort": 849,
        "level": 0.13,
        "bugs": 0.04,
        "time": 47,
        "intelligentContent": 13.55,
        "number_operators": 12,
        "number_operands": 19,
        "number_operators_unique": 5,
        "number_operands_unique": 6,
        "cloc": 12,
        "loc": 40,
        "lloc": 28,
        "mi": 91.19,
        "mIwoC": 53.68,
        "commentWeight": 37.52,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.75,
        "relativeSystemComplexity": 3.75,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 15,
        "totalSystemComplexity": 15,
        "package": "App\\",
        "pageRank": 0.07,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\VirtualMachine",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "App\\ServerInterface"
        ],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\",
        "pageRank": 0.12,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    }
]